AWS_CREDENTIALS:
  ACCESS_KEY: AKIARUP33XTU6NT63S44
  KEY_PAIR: AWS_YC_SEA
  KEY_PATH: /home/osboxes/Documents/AWS_YC_SEA.pem
  SECRET_KEY: xaq4BAxRuiCTFn9V/oKpUhIGxLj5ppwVjTQxroIi
MASTER:
  DNS: ec2-3-1-100-231.ap-southeast-1.compute.amazonaws.com
  ID: i-0622951447ee0c248
  IP: 3.1.100.231
SECURITY_GROUPS:
- sg-0be6223192eecb793
SLAVES:
- DNS: ec2-54-255-245-56.ap-southeast-1.compute.amazonaws.com
  ID: i-0bdbfab13252c1b3e
  IP: 54.255.245.56
